# Project identification
sonar.projectKey=fctcns-website
sonar.projectName=FCTCNS Website
sonar.projectVersion=1.0

# Source code location
sonar.sources=app,public

# Exclusions (files/folders to ignore)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/assets/**,**/*.min.js,**/*.min.css,storage/**,.git/**

# Source encoding
sonar.sourceEncoding=UTF-8
