#!/bin/bash

echo "í·ª TESTING OTHER FUNCTIONALITY"
echo "=============================="

echo "1. Test if admin area loads:"
echo "   http://localhost/fctcns-website/admin/dashboard"
echo ""
echo "2. Test if applications list loads (even if empty):"
echo "   http://localhost/fctcns-website/admin/applications"
echo ""
echo "3. Test if create form loads:"
echo "   http://localhost/fctcns-website/admin/applications/create"
echo ""
echo "4. Test if edit form would load (will redirect if no ID=1):"
echo "   http://localhost/fctcns-website/admin/applications/edit/1"
echo ""
echo "Please test these and tell me:"
echo "- Which ones work?"
echo "- For #2, does it show an empty table or error?"
echo "- For #3, does the form load?"
