#!/bin/bash
# browser-test-guide.sh - Guide for browser testing
echo "🌐 Browser Testing Guide"
echo "========================"
echo ""
echo "OPEN THESE URLs IN YOUR BROWSER:"
echo ""
echo "1. ADMIN PAGES:"
echo "   • http://localhost/fctcns-website/admin/applications"
echo "   • http://localhost/fctcns-website/admin/applications/create"
echo "   • http://localhost/fctcns-website/admin/applications/1"
echo "   • http://localhost/fctcns-website/admin/news"
echo "   • http://localhost/fctcns-website/admin/research"
echo "   • http://localhost/fctcns-website/admin/users"
echo ""
echo "2. PUBLIC PAGES:"
echo "   • http://localhost/fctcns-website/"
echo "   • http://localhost/fctcns-website/about"
echo "   • http://localhost/fctcns-website/contact"
echo ""
echo "3. WHAT TO LOOK FOR:"
echo "   ✓ Page loads without errors"
echo "   ✓ No 'View not found' messages"
echo "   ✓ Content displays correctly"
echo ""
echo "4. IF YOU SEE ERRORS:"
echo "   • Note the exact error message"
echo "   • Check which view file is missing"
echo "   • Run: ./scripts/06-check-controller-views.sh"
echo ""
echo "5. MOST LIKELY ISSUE:"
echo "   If /admin/applications/1 shows 'view not found':"
echo "   • Check if error says 'view.php' or 'show.php'"
echo "   • We created view.php as symlink to show.php"
echo "   • Both ApplicationController and ApplicationsController should work"
echo ""
echo "🎯 Run tests now and report back with any errors!"