#!/bin/bash
# run-quick-tests.sh - Run quick tests after fixes
cd /c/xampp/htdocs/fctcns-website || exit 1

echo "🚀 Quick Tests After Fixes"
echo "========================="
echo ""
echo "TEST THESE URLs IN BROWSER:"
echo ""
echo "1. HOMEPAGE (Database fix):"
echo "   URL: http://localhost/fctcns-website/"
echo "   EXPECTED: Should load without 'Database not found' error"
echo ""
echo "2. APPLICATIONS LIST (Check redirect):"
echo "   URL: http://localhost/fctcns-website/admin/applications"
echo "   EXPECTED: Should show applications list (not redirect to /admin)"
echo ""
echo "3. SINGLE APPLICATION (Correct route):"
echo "   URL: http://localhost/fctcns-website/admin/applications/view/1"
echo "   EXPECTED: Should show application #1 OR 'not found' message"
echo ""
echo "4. CREATE APPLICATION:"
echo "   URL: http://localhost/fctcns-website/admin/applications/create"
echo "   EXPECTED: Should show create form"
echo ""
echo "🔧 If #2 still redirects to /admin:"
echo "   Check if there's a redirect in ApplicationController constructor"
echo "   Look for: header('Location:') or \$this->redirect()"
echo ""
echo "📝 Report back results of ALL 4 tests!"